# Generated by Django 5.2.6 on 2025-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=20)),
                ('strike_price', models.FloatField()),
                ('CE_open_interest', models.BigIntegerField(default=0)),
                ('CE_change_in_oi', models.BigIntegerField(default=0)),
                ('CE_last_price', models.FloatField(default=0.0)),
                ('CE_bid_qty', models.BigIntegerField(default=0)),
                ('CE_bid_price', models.FloatField(default=0.0)),
                ('CE_ask_price', models.FloatField(default=0.0)),
                ('CE_ask_qty', models.BigIntegerField(default=0)),
                ('PE_open_interest', models.BigIntegerField(default=0)),
                ('PE_change_in_oi', models.BigIntegerField(default=0)),
                ('PE_last_price', models.FloatField(default=0.0)),
                ('PE_bid_qty', models.BigIntegerField(default=0)),
                ('PE_bid_price', models.FloatField(default=0.0)),
                ('PE_ask_price', models.FloatField(default=0.0)),
                ('PE_ask_qty', models.BigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='scraper_opt_symbol_6c183a_idx')],
            },
        ),
    ]
