# Generated by Django 5.2.6 on 2025-09-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchain',
            name='current_price',
            field=models.FloatField(default=24),
            preserve_default=False,
        ),
    ]
